[build]
  base = ""
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "https://keeler-dev.netlify.app/*"
  to = "https://keeler.dev/:splat"
  status = 301
  force = true

[context.production.environment]
  NODE_VERSION = "21.0.0"
  NPM_VERSION = "10.2.0"
  NODE_ENV = "production"
