[build]
  base = ""
  publish = "public/"
  command = "yarn build"

[[redirects]]
  from = "https://kind-agnesi-dd5ea1.netlify.com/*"
  to = "https://keeler.dev/:splat"
  status = 301
  force = true

[context.production]
  environment = { "GIT_LFS_ENABLED" = true }
