[build]
  base = ""
  publish = "public/"
  command = "yarn build:prod"

[[redirects]]
  from = "https://kind-agnesi-dd5ea1.netlify.com/*"
  to = "https://keeler.dev/:splat"
  status = 301
  force = true

[context.production.environment]
  GIT_LFS_ENABLED = "true"
  NODE_VERSION = "12.9.1"
  YARN_VERSION = "1.19.1"
